# Generated by Django 3.0.7 on 2020-06-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_test',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(blank=True, max_length=200)),
                ('new_data', models.CharField(blank=True, max_length=200)),
                ('news_content', models.CharField(blank=True, max_length=10000)),
                ('news_emotion', models.CharField(blank=True, max_length=200)),
                ('news_comment', models.CharField(blank=True, max_length=10000)),
            ],
        ),
    ]
