# Generated by Django 3.0.7 on 2020-06-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_trump'),
    ]

    operations = [
        migrations.CreateModel(
            name='trump1',
            fields=[
                ('news_id', models.IntegerField(primary_key=True, serialize=False)),
                ('news_title', models.CharField(max_length=200)),
                ('news_date', models.CharField(max_length=200)),
                ('news_content', models.CharField(max_length=10000)),
                ('news_emotion', models.CharField(max_length=200)),
                ('news_comment', models.CharField(max_length=10000)),
            ],
        ),
    ]
